services:
  web:
    build: ./
    image: idle-quest
    container_name: idle-quest
    ports:
      - "8080:5173"
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: [ "npm", "run", "dev", "--", "--host" ]
